### ISSUE TITLE
Chrome is caching the JS

### ISSUE THREAD

**Issue by ctcreel** [cotiviti/heinzelmannchen#8]
When I synch my repo and relaunch the link those changes aren't showing up in Chrome.  It appears that Chrome is caching the JavaScript.  I think this thread provides a resolution -

http://stackoverflow.com/questions/10736444/chrome-does-not-show-updated-contents-of-external-js-file-which-is-loaded-dynami

**Comment by danistrebel** [comment]
I assume that we can make this part of the r.js build output.

**Comment by ctcreel** [comment]
This was resolved by other means.
